### ISSUE TITLE
Compatible for Corvette-F1 R1 with atrf233

### ISSUE THREAD

**Issue by Jaimin19parmar** [andestech/amazon-freertos#3]
While running the aws_demo program I stuck at the message "wilc1000 initializing.......".
The radio chip on my board is atrf233. So, the wilc1000 driver is compatible with it.?

Board: Corvette-F1 Revision 1- N22
Radio chip: atrf233 
@kevinwang821020 @kjlin168  Can you please help me with the issue.
Thanks !!

**Comment by kevinwang821020** [comment]
Hi @Jaimin19parmar ,
I think it is not working on Corvette-F1 R1 with atrf233.
Because AWS-FreeRTOS has only been qualified on **Corvette-F1 N25** which is another product of AndesTech.
The **Corvette-F1 N25** contains the designated WIFI module(wilc1000), and the wilc1000 driver is **not** compatible with atrf233.

Thank you!

**Comment by kevinwang821020** [comment]
> While running the aws_demo program I stuck at the message "wilc1000 initializing.......".
> The radio chip on my board is atrf233. So, the wilc1000 driver is compatible with it.?
> 
> Board: Corvette-F1 Revision 1- N22
> Radio chip: atrf233
> @kevinwang821020 @kjlin168 Can you please help me with the issue.
> Thanks !!

Hi @Jaimin19parmar ,
I think it is not working on Corvette-F1 R1 with atrf233.
Because AWS-FreeRTOS has only been qualified on **Corvette-F1 N25** which is another product of AndesTech.
The **Corvette-F1 N25** contains the designated WIFI module(**ATWINC1510**) which is compatible with wilc1000 driver(usually for atmel wifi module), but I think the wilc1000 driver is not compatible with atrf233.
Does the atrf233 you mention is at86rf233? As I know, this module is for 802.15.4, not for wifi.

Thank you!

**Comment by Jaimin19parmar** [comment]
Thanks for your kind information @kevinwang821020 
I have checked those other peripherals like LED, Buttons are working properly on my Board.
Can you suggest me any documents or lead on how I can port for at86rf233.

Thank you!!

**Comment by kevinwang821020** [comment]
> Thanks for your kind information @kevinwang821020
> I have checked those other peripherals like LED, Buttons are working properly on my Board.
> Can you suggest me any documents or lead on how I can port for at86rf233.
> 
> Thank you!!

The protocol of at86rf233 is 802.15.4(usually used on Zigbee or thread), and winc1510 is 802.11(usually used on wifi).
So the at86rf233 can't send/receive any data from wifi.
If you want to run AWS-FreeRTOS on Corvette-F1, I think you need to buy another Corvette-F1 which has wifi module(I.e. Corvette-F1 N25).

Hope you find this information helpful!

**Comment by Jaimin19parmar** [comment]
Thanks @kevinwang821020  for the brief suggestion.
I got it.

Thanks :)!
